### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by Tdue21** [RPTools/TokenTool#21]
I have translated TokenTool to danish, but there are a number of issues, that I am unable to handle through translation of i18n properties alone. 

### Portrait Options
This button and dropdown are not currently translatable: 
![image](https://user-images.githubusercontent.com/2953375/54361871-39b1af80-4668-11e9-985a-52ac4e3f223a.png)

I realize that the Custom Color dialog is probably a standard component, but still, it should be translatable. 

### Overlay Options

Likewise the default overlay folders and images are also fixed texts, that is not translatable. 
![image](https://user-images.githubusercontent.com/2953375/54362256-e4c26900-4668-11e9-8cf6-4e7f95dc09c8.png)

### Manage Overlays Dialog

Finally, the dialog for managing overlays has a couple of issues as well. The default overlays are not translatable as they seem to be hardcoded. 

![image](https://user-images.githubusercontent.com/2953375/54363120-8eeec080-466a-11e9-8cee-12e985849f46.png)

Again, the overlay name is hardcoded, as well as the file type, if it is a Photoshop file. 

![image](https://user-images.githubusercontent.com/2953375/54363095-80080e00-466a-11e9-843a-be5f274ba0a7.png)

**Comment by Azhrei** [comment]
This is great — thank you!  I'll talk to Jamz about getting this merged, and we'll look into externalizing these other strings.

**Comment by JamzTheMan** [comment]
I'm pretty sure I now have everything externalized that can be. What can't be translated, or can't be without some pain/issues are:

 * Colors - Transparent and the other color names all come from the FX Color Picker. If that control doesn't have i18n translations, we would have to manually do that for all the colors (yuck).
 * The default overlays/folders are in fact "hard coded" as they are resource package names. Al the overlays are stored like any other java resource and reflection is used to extract and save them on demand.  Although, once "extracted" they can be renamed if the user wants to.  We would have to do some manual i18n work here and I would treat that as it's own enhancement issue to be created.
 * I think the file type names may be coming from the lib directly, Although there is a chance it's not. However, it's a proper name so "Adobe Photoshop" would be the same in all languages? (I'm just guessing here) but I suppose we could just put PSD here to match PNG/JPG and drop the "Image" and "File" wording?

*Note* If you can, double check your danish translation. There was a merge conflict because I had new properties added in 2.1, but I think I got the changes ok.
